# Generated by Django 5.0.3 on 2024-03-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_delegate_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='aiesecer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='entity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
