# Generated by Django 5.0.3 on 2024-03-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_delegate_aiesecer_delegate_entity_delegate_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/speakers'),
        ),
    ]
