# Generated by Django 5.0.3 on 2024-03-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='sessions',
            field=models.ManyToManyField(blank=True, to='API.session'),
        ),
    ]
