# Generated by Django 5.0.3 on 2024-03-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_score_session_event_alter_event_sessions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-score']},
        ),
    ]
