# Generated by Django 5.0.3 on 2024-04-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_remove_delegate_aiesecer_delegate_aiesecemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
